version: '3'

services:
  web:
    build: .
    image: patch-and-label
    volumes:
      - '~/Desktop/input:/work/input'
      # - '/Volumes/HDD/tile_images:/work/Patch-and-label/input'
    working_dir: /work
    container_name: patch-and-label
    tty: true
    stdin_open: true
